(module
  (import "env" "memory" (memory 4))
  (import "env" "saveSize" (func $size (result i32)))
  (import "env" "saveRead" (func $read (param i32 i32) (result i32)))
  (import "env" "saveWrite" (func $write (param i32 i32) (result i32)))
  (import "env" "saveDelete" (func $delete (result i32)))
  (data (i32.const 81920) "hello")
  (global $initial (mut i32) (i32.const 0))
  (func $init (global.set $initial (call $size)))
  (start $init)
  (func (export "initial") (result i32) (global.get $initial))
  (func (export "size") (result i32) (call $size))
  (func (export "read") (param i32 i32) (result i32) (call $read (local.get 0) (local.get 1)))
  (func (export "write") (param i32 i32) (result i32) (call $write (local.get 0) (local.get 1)))
  (func (export "delete") (result i32) (call $delete))
  (func (export "upd"))
)
